### PR TITLE
Remove .DS_Store

### PR DESCRIPTION
**Pull request by arbusam**
Removing .DS_Store, an unneeded file that should be in the .gitignore (I added it there).

### CODE REVIEW

**Comment by TheCyberCoder1** [comment]
I am afraid that deleting DS_Store  says that the code is conflicting could you please check how for it to 'appeal' to github

**Comment by arbusam** [comment]
Press resolve conflicts and then it should ask, do you want to keep or not keep .DS_Store.

**Comment by TheCyberCoder1** [comment]
review conflict is grey and will not let me press/activate it

**Comment by arbusam** [comment]
I am closing this issue because it will create more conflicts than it's worth.

**Pull request closed without merging**
